### ISSUE TITLE
Add Matano to security tools

### ISSUE THREAD

**Issue by shaeqahmed** [mikeroyal/Open-Source-Security-Guide#24]
Hi @mikeroyal can we add Matano to the security tools section :) Thanks for maintaining this guide!

Listing info:
Matano - Open source cloud-native security lake platform (SIEM alternative) for threat hunting, Python detections-as-code, and incident response on AWS 🦀

**Comment by mikeroyal** [comment]
Hi, a PR has been made to it. Thank you for your suggestion.
